language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
# coverage 4.3.2 fails with py 2.6:
# https://bitbucket.org/ned/coveragepy/issues/555/coverage-432-claims-support-for-py26-but
  - "pip install coverage==4.3.1 pytest-cov coveralls"
  - "if [[ ${TRAVIS_PYTHON_VERSION%.*} -gt 2 ]]; then pip install -r requirements-py3.txt; fi"
# command to run tests
script: py.test -vv tests --cov osbs
# run in a docker container
sudo: false
notifications:
  email: false
after_success: "coveralls"
deploy:
  provider: pypi
  user: bkabrda
  on:
    tags: true
  password:
    secure: Q4pXe0ARf2Mj7ZEqEICpzW6SBB554PxVPKErJkUcaD4V3zO3e/Ckbrk0aHeCMCPZlD5i/tfBXRMsMJhcvQht+jXTwUo5VD55WvkKBmpvQbJBsvmrIvrX+3C8SxVYXyLiSklQxCdGMCE/EN9dmQVI2574BQsXR43uVhwOzuL2V3k=
